name: Compile standalone for Windows

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      UPX_VERSION: "5.0.2"
      UPX_DIR: "${{ github.workspace }}/tools/upx"
      VERSION: "0.8.3"

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set app version
        shell: bash
        run: |
          echo "APP_VERSION=${VERSION}" >> "$GITHUB_ENV"

      - name: Set VERSION for push
        if: github.event_name == 'push'
        shell: bash
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "APP_VERSION=${VERSION}+${SHORT_SHA}" >> "$GITHUB_ENV"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Generate _version.py
        run: |
          python tools/write_version.py

      - name: Download UPX (Windows)
        shell: pwsh
        run: |
          $zip = "$env:RUNNER_TEMP\upx.zip"
          Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v${env:UPX_VERSION}/upx-${env:UPX_VERSION}-win64.zip" -OutFile $zip
          Expand-Archive -Path $zip -DestinationPath $env:RUNNER_TEMP\upx -Force
          $exepath = Get-ChildItem -Path $env:RUNNER_TEMP\upx -Recurse -Filter upx.exe | Select-Object -First 1
          New-Item -ItemType Directory -Force -Path $env:UPX_DIR | Out-Null
          Copy-Item $exepath.FullName -Destination "$env:UPX_DIR\upx.exe" -Force
          echo "$env:UPX_DIR" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build Executable for Windows
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: StartLive.py
          # mingw64: true
          # Nuitka currently do not support mingw64 for Python 3.13
          # Wait for update in future
          msvc: latest
          mode: standalone
          enable-plugins: pyside6,upx
          company-name: "Radekyspec"
          product-name: "StartLive开播器"
          file-description: "StartLive开播器"
          file-version: ${{ env.VERSION }}
          windows-icon-from-ico: "resources/icon_left.ico"
          windows-console-mode: "disable"
          noinclude-setuptools-mode: "nofollow"
          noinclude-pytest-mode: "nofollow"
          noinclude-unittest-mode: "nofollow"
          include-data-dir: "resources=resources"
          noinclude-data-files: |
            "resources/version.json"
            "resources/icon_left_macOS.ico"
          onefile-no-compression: true
          upx-disable-cache: true
          deployment: true

      - name: Flatten output
        run: |
          mkdir -p output
          mv build/StartLive.dist/* output/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StartLive-v${{ env.APP_VERSION }}-${{ runner.os }}-standalone
          path: |
            output/
          include-hidden-files: true
